#!/usr/bin/env rexx
/*
 * Test Google Docs APPEND with HEREDOC
 * Demonstrates elegant multi-line content insertion
 */

PARSE ARG credFile, docId

SAY "Google Docs APPEND with HEREDOC Demo"
SAY "===================================="
SAY ""

LET documentId = docId

/* Capture multi-line content with HEREDOC */
LET reportContent = <<REPORT
=== DAILY REPORT ===

Date: 2025-09-30
Generated by: RexxJS

Summary:
--------
This is a multi-line report generated using HEREDOC syntax.
It demonstrates the elegant way to insert formatted content
into Google Docs.

Key Points:
- HEREDOC makes multi-line content natural
- No need to escape quotes or newlines
- Content is interpolated cleanly into commands

Conclusion:
This approach is far more elegant than concatenating strings!

=== END REPORT ===

REPORT

REQUIRE "./extras/addresses/provisioning-and-orchestration/address-gcp.js"

ADDRESS GCP

SAY "Step 1: Connecting to document..."
"DOCS CONNECT document={documentId}"

IF RC \= 0 THEN DO
  SAY "✗ FAILED: " || ERRORTEXT
  EXIT 1
END

SAY "✓ Connected to: " || RESULT.document.title
SAY ""

SAY "Step 2: Appending HEREDOC content to end of document..."
"DOCS APPEND text={reportContent}"

IF RC \= 0 THEN DO
  SAY "✗ FAILED: " || ERRORTEXT
  EXIT 1
END

SAY "✓ " || RESULT.message
SAY "  Characters appended: " || RESULT.textLength
SAY "  Inserted at index: " || RESULT.insertIndex
SAY ""

SAY "Step 3: Reading updated document..."
"DOCS READ"

IF RC \= 0 THEN DO
  SAY "✗ FAILED: " || ERRORTEXT
  EXIT 1
END

SAY "✓ Document now contains " || RESULT.length || " characters"
SAY ""
SAY "✓ Demo complete!"
SAY ""
SAY "View at: https://docs.google.com/document/d/" || documentId

EXIT 0
